Update how tom builds deptables
cf-bottom/self pull request #59
Opened 2020-11-20 18:00 UTC by Lex-2008

----

#

2020-11-21 17:03 UTC, cf-bottom commented
Thank you for submitting a pull request! Maybe @olehermanse can review this?

2021-01-12 11:28 UTC, Lex-2008 commented
ready 2b reviewed!

2021-01-12 12:20 UTC, olehermanse commented
@Lex-2008 could you run this and paste the output here in a comment?

2021-01-13 13:05 UTC, Lex-2008 commented
Text output:
```
[lex@flower2 cf-bottom]$ python -m tom -i -t cf-bottom -l info
<@cf-bottom> depstable: 3.12.x,3.15.x,master
fatal: remote upstream already exists.
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
Unpacking objects: 100% (13/13), 4.04 KiB | 229.00 KiB/s, done.
remote: Total 13 (delta 7), reused 7 (delta 7), pack-reused 5
From github.com:cfengine/buildscripts
 * branch            master     -> FETCH_HEAD
   d4d331c..5b55383  master     -> upstream/master
Switched to branch 'master'
Your branch is behind 'upstream/master' by 6 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 5b55383 Merge pull request #793 from olehermanse/mailmap
From github.com:cfengine/buildscripts
 * branch            3.12.x     -> FETCH_HEAD
Switched to branch '3.12.x'
Your branch is up to date with 'upstream/3.12.x'.
HEAD is now at 8331bcc Merge pull request #784 from Lex-2008/ENT-5363-suse15-3.12.x
Already up to date.
From github.com:cfengine/buildscripts
 * branch            3.15.x     -> FETCH_HEAD
Switched to branch '3.15.x'
Your branch is up to date with 'upstream/3.15.x'.
HEAD is now at 7f335cf Merge pull request #783 from Lex-2008/ENT-5363-suse15-3.15.x
Already up to date.
From github.com:cfengine/buildscripts
 * branch            master     -> FETCH_HEAD
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.
HEAD is now at 5b55383 Merge pull request #793 from olehermanse/mailmap
Already up to date.
From github.com:cfengine/buildscripts
 * branch            master     -> FETCH_HEAD
Already on 'master'
Your branch is up to date with 'upstream/master'.
HEAD is now at 5b55383 Merge pull request #793 from olehermanse/mailmap
[WARNING] didn't find dep in line [| lcov             | 1.14   | 1.14   | 1.14   |]
[WARNING] didn't find dep in line [| git              |        |        |        |]
[WARNING] didn't find dep in line [| rsync            |        |        |        |]
[WARNING] didn't find dep in line [| libgcc                                                                           |        |        |        | AIX and Solaris only     |]
Switched to a new branch 'deptables-2021-01-13_14_03_25_765604'
[deptables-2021-01-13_14_03_25_765604 236620b] Update dependency tables
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 596 bytes | 99.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
remote: 
remote: Create a pull request for 'deptables-2021-01-13_14_03_25_765604' on GitHub by visiting:
remote:      https://github.com/Lex-2008/buildscripts/pull/new/deptables-2021-01-13_14_03_25_765604
remote: 
To github.com:Lex-2008/buildscripts.git
 * [new branch]      deptables-2021-01-13_14_03_25_765604 -> deptables-2021-01-13_14_03_25_765604
[INFO] SLACK: <@con>: Dependency tables:
PR: https://github.com/cfengine/buildscripts/pull/794
<@cf-bottom> 
```
Note that created PR doesn't change anything, since tables were already updated by Tom in https://github.com/cfengine/buildscripts/pull/790

2021-01-13 13:08 UTC, cf-bottom commented
Alright, I triggered a build:

[![Build Status](https://ci.cfengine.com//buildStatus/icon?job=pr-pipeline&build=6014)](https://ci.cfengine.com//job/pr-pipeline/6014/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6014/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6014/

2021-01-13 14:47 UTC, vpodzime reviewed
```
[WARNING] didn't find dep in line [| lcov             | 1.14   | 1.14   | 1.14   |]
```
this line looks correct and should be parsed, right?

2021-01-13 14:47 UTC, vpodzime commented on tom/dependencies.py
> +                row = ( ["CFEngine version"] +
Please drop the spaces after and before parentheses.

2021-01-13 14:47 UTC, vpodzime commented on tom/dependencies.py
> +                match = re.match('\| \[([a-z0-9-]*)\]\((.*?)\) ', line, flags=re.IGNORECASE)
A matching example would be nice here.

2021-01-13 14:59 UTC, Lex-2008 commented
> ```
> [WARNING] didn't find dep in line [| lcov             | 1.14   | 1.14   | 1.14   |]
> ```
> 
> this line looks correct and should be parsed, right?

Not really. All other dependencies always have URL in them, while these three come from [Build dependencies](https://github.com/cfengine/buildscripts/blob/master/README.md#build-dependencies) table and don't have URLs.

2021-01-14 00:46 UTC, olehermanse commented
> Not really. All other dependencies always have URL in them, while these three come from Build dependencies table and don't have URLs.

@Lex-2008 So they are correct. You are contradicting yourself in the same sentence ;)

2021-01-14 00:50 UTC, olehermanse requested changes
The commit message (and PR title) should explain what this changes.

Tom built deptables before, you updated it, Tom still builds deptables. What is the difference?

2021-01-26 13:33 UTC, olehermanse approved these changes
Looks good to me now. All the regex is quite cryptic to me, but thanks for the examples and comments.

2021-01-26 13:33 UTC, cf-bottom approved these changes
I trust @olehermanse, approved!

2021-01-26 14:06 UTC, vpodzime commented on tom/dependencies.py
> +                        ( [note] if has_notes else [] )
Some more unnecessary spaces inside parentheses.

2021-01-27 14:03 UTC, vpodzime approved these changes
ACK

2021-01-27 20:42 UTC, merged